/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import models.Box;
import models.Truck;
import models.Worker;
import utils.Threads;

/**
 *
 * @author alvar
 */
public class Scene extends javax.swing.JFrame {

    /**
     * Creates new form Scene
     */
    public Scene() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scenePanel = new javax.swing.JPanel();
        box1 = new javax.swing.JLabel();
        worker1 = new javax.swing.JLabel();
        truck1 = new javax.swing.JLabel();
        worker2 = new javax.swing.JLabel();
        box2 = new javax.swing.JLabel();
        truck2 = new javax.swing.JLabel();
        box11 = new javax.swing.JLabel();
        box10 = new javax.swing.JLabel();
        box12 = new javax.swing.JLabel();
        box13 = new javax.swing.JLabel();
        box14 = new javax.swing.JLabel();
        box15 = new javax.swing.JLabel();
        box16 = new javax.swing.JLabel();
        box3 = new javax.swing.JLabel();
        box4 = new javax.swing.JLabel();
        box5 = new javax.swing.JLabel();
        box6 = new javax.swing.JLabel();
        box7 = new javax.swing.JLabel();
        box8 = new javax.swing.JLabel();
        box9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2000, 1600));
        setMinimumSize(new java.awt.Dimension(300, 100));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        box1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        worker1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/worker1-left.png"))); // NOI18N

        truck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/truck.png"))); // NOI18N

        worker2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/worker2-left.png"))); // NOI18N

        box2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        truck2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/truck2.png"))); // NOI18N

        box11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        box9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N

        javax.swing.GroupLayout scenePanelLayout = new javax.swing.GroupLayout(scenePanel);
        scenePanel.setLayout(scenePanelLayout);
        scenePanelLayout.setHorizontalGroup(
            scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scenePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scenePanelLayout.createSequentialGroup()
                        .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(scenePanelLayout.createSequentialGroup()
                                .addComponent(box1)
                                .addGap(18, 18, 18)
                                .addComponent(box8))
                            .addGroup(scenePanelLayout.createSequentialGroup()
                                .addComponent(box2)
                                .addGap(18, 18, 18)
                                .addComponent(box7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                        .addComponent(worker1))
                    .addGroup(scenePanelLayout.createSequentialGroup()
                        .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(scenePanelLayout.createSequentialGroup()
                                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box12)
                                    .addComponent(box11)
                                    .addComponent(box9))
                                .addGap(18, 18, 18)
                                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box16)
                                    .addComponent(box15)
                                    .addComponent(box14)
                                    .addComponent(box13)))
                            .addGroup(scenePanelLayout.createSequentialGroup()
                                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box3)
                                    .addComponent(box4))
                                .addGap(18, 18, 18)
                                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box5)
                                    .addComponent(box6))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(scenePanelLayout.createSequentialGroup()
                        .addComponent(box10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(worker2)))
                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scenePanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(truck2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scenePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truck1)))
                .addContainerGap())
        );
        scenePanelLayout.setVerticalGroup(
            scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scenePanelLayout.createSequentialGroup()
                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scenePanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(truck2))
                    .addGroup(scenePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(scenePanelLayout.createSequentialGroup()
                                .addComponent(box5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(box6))
                            .addGroup(scenePanelLayout.createSequentialGroup()
                                .addComponent(box4)
                                .addGap(11, 11, 11)
                                .addComponent(box3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(worker1)
                            .addGroup(scenePanelLayout.createSequentialGroup()
                                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(box7)
                                    .addComponent(box2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(box1)
                                    .addComponent(box8))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(truck1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scenePanelLayout.createSequentialGroup()
                        .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(worker2)
                            .addGroup(scenePanelLayout.createSequentialGroup()
                                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scenePanelLayout.createSequentialGroup()
                                        .addComponent(box13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(scenePanelLayout.createSequentialGroup()
                                        .addComponent(box12)
                                        .addGap(14, 14, 14)))
                                .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(scenePanelLayout.createSequentialGroup()
                                        .addComponent(box11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(box10)
                                        .addGap(11, 11, 11)
                                        .addComponent(box9))
                                    .addGroup(scenePanelLayout.createSequentialGroup()
                                        .addGroup(scenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(scenePanelLayout.createSequentialGroup()
                                                .addComponent(box14)
                                                .addGap(35, 35, 35))
                                            .addComponent(box15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(box16)))))
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scenePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scenePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        List<Box> firstBoxPile = new ArrayList<Box>();
        List<Box> secondBoxPile = new ArrayList<Box>();
        Truck truck1 = new Truck(16, "ENG10");
        Truck truck2 = new Truck(16, "C012");
        Worker worker1 = new Worker("JAVA", false, false, false);
        Worker worker2 = new Worker("DART", false, false, false);

        for (int i = 1; i <= 8; i++) {
            firstBoxPile.add(new Box());
        }
        for (int i = 1; i <= 8; i++) {
            secondBoxPile.add(new Box());
        }
       
        
        Threads t1 = new Threads("THREAD WORKER 1", firstBoxPile, truck1);
        Threads t2 = new Threads("THREAD WORKER 2", secondBoxPile, truck2);

        t1.setWorker(worker1);
        t1.setWorkerLabel(this.worker1);
        t1.setFrame(this);
        t1.setTruckLabel(this.truck1);

        t2.setWorkerLabel(this.worker2);
        t2.setWorker(worker2);
        t2.setFrame(this);
        t2.setTruckLabel(this.truck2);

        t1.start();
        t2.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scene().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel box1;
    private javax.swing.JLabel box10;
    private javax.swing.JLabel box11;
    private javax.swing.JLabel box12;
    private javax.swing.JLabel box13;
    private javax.swing.JLabel box14;
    private javax.swing.JLabel box15;
    private javax.swing.JLabel box16;
    private javax.swing.JLabel box2;
    private javax.swing.JLabel box3;
    private javax.swing.JLabel box4;
    private javax.swing.JLabel box5;
    private javax.swing.JLabel box6;
    private javax.swing.JLabel box7;
    private javax.swing.JLabel box8;
    private javax.swing.JLabel box9;
    private javax.swing.JPanel scenePanel;
    private javax.swing.JLabel truck1;
    private javax.swing.JLabel truck2;
    private javax.swing.JLabel worker1;
    private javax.swing.JLabel worker2;
    // End of variables declaration//GEN-END:variables
}
